@baseUrl = http://127.0.0.1:8000/api/v1

### Registro exitoso de academia
POST {{baseUrl}}/auth/academy/register
Content-Type: application/json

{
  "academy_name": "Union MMA",
  "admin_first_name": "Dante",
  "admin_last_name": "Ramirez",
  "email": "admin.union@example.com",
  "password": "d4nt3r4d123"
}

### Reintento con academia duplicada
POST {{baseUrl}}/auth/academy/register
Content-Type: application/json

{
  "academy_name": "Union MMA",
  "admin_first_name": "Otro",
  "admin_last_name": "Admin",
  "email": "otro.union@example.com",
  "password": "d4nt3r4d123"
}

### Inicio de sesión con el admin creado
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin.union@example.com",
  "password": "d4nt3r4d123"
}
